### ISSUE TITLE
Signup/Register Page

### ISSUE THREAD

**Issue by neerajpadarthi** [shannu1221/CS5551_Team8_Project#1]

**Comment by shannu1221** [comment]
@htata31  i implemented Signup/Register Page here. Please go through my implementation and complete the review.
![resgister here](https://user-images.githubusercontent.com/42659018/46214567-133dc900-c301-11e8-99c5-e1694c6cc3dd.PNG)

**Comment by htata31** [comment]
Reviewed the implementation code.
