### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by neerajpadarthi** [shannu1221/CS5551_Team8_Project#5]
Definition of done: On entering to HomePage should able to see a welcome message, text fields for entering the destination, From and To dates, Budget and should be able to select his interests from the dropdown. HomePage should also consists of buttons for navigating to Contact Us page, About Us page and also a Logout button which prompts user to Login page

**Comment by shannu1221** [comment]
![homepage1](https://user-images.githubusercontent.com/42659018/46217657-328c2480-c308-11e8-8782-0ba809984d28.PNG)
![homepage2](https://user-images.githubusercontent.com/42659018/46217658-328c2480-c308-11e8-87f6-6ad3146c11bb.PNG)
Reviewed the Implementation.It looks good.
