### ISSUE TITLE
UML Diagram

### ISSUE THREAD

**Issue by neerajpadarthi** [shannu1221/CS5551_Team8_Project#6]
Definition of Done: Class, Sequence and architecture diagram for Increment 1 needs to drawn.

**Comment by shannu1221** [comment]
@pallavidesai  please review the commits that i made for this strory.
![travelapparchitecture](https://user-images.githubusercontent.com/42659018/46160864-79671500-c249-11e8-8646-59127f62b8e0.PNG)
![travelappclass](https://user-images.githubusercontent.com/42659018/46160865-79671500-c249-11e8-97a8-3fd1f800f963.png)
![travelappsequence](https://user-images.githubusercontent.com/42659018/46160866-79671500-c249-11e8-90d5-a3928e030618.png)

**Comment by pallavidesai** [comment]
@shannu1221  I reviewed the commit done by you. It looks good.

**Comment by pallavidesai** [comment]
Commit has been fully reviewed.
